### ISSUE TITLE
웹앱 프로그래밍 아키텍처 구상

### ISSUE THREAD

**Issue by TAKKWANG** [SESAC-AIoT/kim#1]

**Comment by TAKKWANG** [comment]
웹서버 개념 이해 필요, 아파치, nginx,

**Comment by Maeng89** [comment]
flask가 웹서버 기능을 함께하므로 아차피 불필요

**Comment by Maeng89** [comment]
<기획 초안>

![Image](https://user-images.githubusercontent.com/79052421/219983789-c93abcb3-a663-4134-8999-a46451932df7.png)
